In [1]:
import numpy as np

In [2]:
myarr= np.array([[3,4,34,2]],np.int64)

In [3]:
myarr[0,1]

4

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1]=69
myarr

array([[ 3, 69, 34,  2]], dtype=int64)

# Array Creation

### 1. Conversion from other Python structures (eg: lists, tuples)

In [7]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
listarray.dtype

dtype('int32')

In [10]:
listarray.shape

(3, 3)

In [11]:
listarray.size

9

In [12]:
np.array({2,3,5})

array({2, 3, 5}, dtype=object)

### 2. Intrinsic numpy array creation objects (eg: arange, ones, xeros,etc.)

In [13]:
zeros= np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zeros.dtype

dtype('float64')

In [15]:
rng=np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#gives 5 equally spaced ele from 1 to 5
lspace=np.linspace(1,5,4) 
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [17]:
emp=np.empty((4,6))
emp # empty array with random ele

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86922637e-306, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        1.33511290e-306, 1.78019082e-306, 8.45559303e-307],
       [8.06613465e-308, 6.89810244e-307, 1.22387550e-307,
        2.22522596e-306, 8.34423917e-308, 9.79107193e-307]])

In [18]:
emp_like =np.empty_like(lspace)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [19]:
ide =np.identity(6)
ide #identity matrix 

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
arr= np.arange(69)
print(arr.shape)
arr

(69,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68])

In [21]:
arr=arr.reshape(3,23)
print(arr.shape)
arr

(3, 23)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
        39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
        62, 63, 64, 65, 66, 67, 68]])

In [22]:
arr=arr.ravel()
print(arr.shape)
arr

(69,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68])

# NUMPY AXIS

In [23]:
x=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [24]:
ar.sum(axis=0) # axis 0 -sum of columns

array([12,  8,  9])

In [25]:
ar.sum(axis=1) # axis 0 -sum of rows

array([ 6, 15,  8])

In [26]:
ar.T #transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [27]:
ar.flat #iterator

In [28]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [29]:
ar.ndim #dimension
ar.size #no. of elements
ar.nbytes #no. of bytes used

36

arguments in 1D array

In [30]:
one =np.array([1,3,4,69,5])
one.argmax() #give index of max ele
one.argmin() #give index of min ele
one.argsort() #gives index as sorted array

array([0, 1, 2, 4, 3], dtype=int64)

arguments in 2D array

In [31]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [32]:
ar.argmin() 

8

In [33]:
ar.argmax()

6

In [34]:
ar.argmax(axis=0) #gives indexes of max ele of columns

array([2, 1, 1], dtype=int64)

In [35]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [36]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [37]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [38]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

Mathematical operations

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar2=np.array([[1, 0, 3],[2, 5, 1],[3, 1, 0]])
ar2

array([[1, 0, 3],
       [2, 5, 1],
       [3, 1, 0]])

In [41]:
ar*ar2 #numpy allows mathematical operations

array([[ 1,  0,  9],
       [ 8, 25,  6],
       [21,  1,  0]])

In [42]:
[1, 0, 3]+[2, 5, 1] #normal python lists concatinate

[1, 0, 3, 2, 5, 1]

In [43]:
np.sqrt(ar*ar2) #square root
ar.sum() #sum of all elements
ar.max() #max ele not index
ar.min() #min ele

0

Finding ele in arr

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [46]:
type(np.where(ar>5))

tuple

In [47]:
np.count_nonzero(ar)

8

In [48]:
np.nonzero(ar) #1st gives row no. 2nd gives column no.

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [49]:
ar[1,2]=0
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [50]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

NUMPY uses less space

In [51]:
import sys

In [52]:
py_ar=[0,4,69,2]

In [53]:
np_ar=np.array(py_ar)

In [54]:
sys.getsizeof(1)*len(py_ar)

112

In [55]:
np_ar.itemsize* np_ar.size

16